services:
  azure-bay:
    build: .
    container_name: azure_bay_app
    ports:
      - "8080:80"
    restart: always
    networks:
      - azure_network

networks:
  azure_network:
    driver: bridge
